/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./src/components/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./src/components/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./src/components/accordion/AccordionTrigger.vue')['default']
    Alert: typeof import('./src/components/alert/Alert.vue')['default']
    AlertDescription: typeof import('./src/components/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./src/components/alert/AlertTitle.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    CardContent: typeof import('./src/components/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/card/CardTitle.vue')['default']
    Input: typeof import('./src/components/input/Input.vue')['default']
    Label: typeof import('./src/components/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/textarea/Textarea.vue')['default']
  }
}
