/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/accordion/Accordion.vue')['default']
    AccordionContent: typeof import('./src/components/accordion/AccordionContent.vue')['default']
    AccordionItem: typeof import('./src/components/accordion/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./src/components/accordion/AccordionTrigger.vue')['default']
    Alert: typeof import('./src/components/alert/Alert.vue')['default']
    AlertDescription: typeof import('./src/components/alert/AlertDescription.vue')['default']
    AlertDialog: typeof import('./src/components/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./src/components/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/alert-dialog/AlertDialogTrigger.vue')['default']
    AlertTitle: typeof import('./src/components/alert/AlertTitle.vue')['default']
    AspectRatio: typeof import('./src/components/aspect-ratio/AspectRatio.vue')['default']
    Avatar: typeof import('./src/components/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/avatar/AvatarImage.vue')['default']
    Badge: typeof import('./src/components/badge/Badge.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/Breadcrumb.vue')['default']
    BreadcrumbEllipsis: typeof import('./src/components/breadcrumb/BreadcrumbEllipsis.vue')['default']
    BreadcrumbItem: typeof import('./src/components/breadcrumb/BreadcrumbItem.vue')['default']
    BreadcrumbLink: typeof import('./src/components/breadcrumb/BreadcrumbLink.vue')['default']
    BreadcrumbList: typeof import('./src/components/breadcrumb/BreadcrumbList.vue')['default']
    BreadcrumbPage: typeof import('./src/components/breadcrumb/BreadcrumbPage.vue')['default']
    BreadcrumbSeparator: typeof import('./src/components/breadcrumb/BreadcrumbSeparator.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Calendar: typeof import('./src/components/calendar/Calendar.vue')['default']
    CalendarCell: typeof import('./src/components/calendar/CalendarCell.vue')['default']
    CalendarCellTrigger: typeof import('./src/components/calendar/CalendarCellTrigger.vue')['default']
    CalendarGrid: typeof import('./src/components/calendar/CalendarGrid.vue')['default']
    CalendarGridBody: typeof import('./src/components/calendar/CalendarGridBody.vue')['default']
    CalendarGridHead: typeof import('./src/components/calendar/CalendarGridHead.vue')['default']
    CalendarGridRow: typeof import('./src/components/calendar/CalendarGridRow.vue')['default']
    CalendarHeadCell: typeof import('./src/components/calendar/CalendarHeadCell.vue')['default']
    CalendarHeader: typeof import('./src/components/calendar/CalendarHeader.vue')['default']
    CalendarHeading: typeof import('./src/components/calendar/CalendarHeading.vue')['default']
    CalendarNextButton: typeof import('./src/components/calendar/CalendarNextButton.vue')['default']
    CalendarPrevButton: typeof import('./src/components/calendar/CalendarPrevButton.vue')['default']
    Card: typeof import('./src/components/card/Card.vue')['default']
    CardContent: typeof import('./src/components/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/card/CardTitle.vue')['default']
    Input: typeof import('./src/components/input/Input.vue')['default']
    Label: typeof import('./src/components/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/textarea/Textarea.vue')['default']
  }
}
